### PR TITLE
Update Kif's bdd support rating and footnote

### PR DESCRIPTION
**Pull request by mitochondrion**
Hey Joe, I updated the Kif BDD support rating to indicate that it can be used with BDD frameworks.

### CODE REVIEW

**Comment by joemasilotti** [comment]
That's awesome, thanks Alex! What do you think about moving the heart to the yellow level as it's not supported out of the box? "Supported with caveats."

**Comment by mitochondrion** [comment]
Sure!  I'll amend the commit.

**Comment by mitochondrion** [comment]
Ok changed it to yellow.

**Comment by joemasilotti** [comment]
Awesome, thanks again!

**Pull request merged**
